# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'configurationGUI.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(970, 668)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 0, 971, 721))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackedWidget.sizePolicy().hasHeightForWidth())

        self.stackedWidget.setSizePolicy(sizePolicy)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.titleConfigurationLabel = QtWidgets.QLabel(self.page)
        self.titleConfigurationLabel.setGeometry(QtCore.QRect(360, 10, 219, 37))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.titleConfigurationLabel.sizePolicy().hasHeightForWidth())
        self.titleConfigurationLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)

        self.titleConfigurationLabel.setFont(font)
        self.titleConfigurationLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.titleConfigurationLabel.setObjectName("titleConfigurationLabel")
        self.startButton = QtWidgets.QPushButton(self.page)
        self.startButton.setGeometry(QtCore.QRect(380, 470, 161, 71))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)

        self.startButton.setFont(font)
        self.startButton.setObjectName("startButton")

        self.personDataFrame = QtWidgets.QFrame(self.page)
        self.personDataFrame.setGeometry(QtCore.QRect(30, 70, 221, 291))
        self.personDataFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.personDataFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.personDataFrame.setObjectName("personDataFrame")

        self.nameLabel = QtWidgets.QLabel(self.personDataFrame)
        self.nameLabel.setGeometry(QtCore.QRect(30, 20, 58, 14))
        self.nameLabel.setObjectName("nameLabel")

        self.ageLabel = QtWidgets.QLabel(self.personDataFrame)
        self.ageLabel.setGeometry(QtCore.QRect(30, 70, 31, 16))
        self.ageLabel.setObjectName("ageLabel")

        self.genderLabel = QtWidgets.QLabel(self.personDataFrame)
        self.genderLabel.setGeometry(QtCore.QRect(30, 120, 58, 14))
        self.genderLabel.setObjectName("genderLabel")

        self.heightLabel = QtWidgets.QLabel(self.personDataFrame)
        self.heightLabel.setGeometry(QtCore.QRect(30, 170, 58, 14))
        self.heightLabel.setObjectName("heightLabel")

        self.weightLabel = QtWidgets.QLabel(self.personDataFrame)
        self.weightLabel.setGeometry(QtCore.QRect(30, 220, 58, 14))
        self.weightLabel.setObjectName("weightLabel")
        self.nameEdit = QtWidgets.QLineEdit(self.personDataFrame)
        self.nameEdit.setGeometry(QtCore.QRect(30, 40, 113, 24))
        self.nameEdit.setObjectName("nameEdit")
        self.ageEdit = QtWidgets.QLineEdit(self.personDataFrame)
        self.ageEdit.setGeometry(QtCore.QRect(30, 90, 113, 24))
        self.ageEdit.setObjectName("ageEdit")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.personDataFrame)
        self.lineEdit_3.setGeometry(QtCore.QRect(30, 190, 113, 24))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.personDataFrame)
        self.lineEdit_4.setGeometry(QtCore.QRect(30, 240, 113, 24))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.genderBox = QtWidgets.QComboBox(self.personDataFrame)
        self.genderBox.setGeometry(QtCore.QRect(30, 140, 78, 24))
        self.genderBox.setObjectName("genderBox")
        self.genderBox.addItem("")
        self.genderBox.addItem("")
        self.genderBox.addItem("")
        self.gesturesFrame = QtWidgets.QFrame(self.page)
        self.gesturesFrame.setGeometry(QtCore.QRect(350, 70, 221, 291))
        self.gesturesFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.gesturesFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.gesturesFrame.setObjectName("gesturesFrame")
        self.nGesturesLabel = QtWidgets.QLabel(self.gesturesFrame)
        self.nGesturesLabel.setGeometry(QtCore.QRect(30, 20, 131, 16))
        self.nGesturesLabel.setObjectName("nGesturesLabel")
        self.nGesturesEdit = QtWidgets.QLineEdit(self.gesturesFrame)
        self.nGesturesEdit.setGeometry(QtCore.QRect(30, 40, 113, 24))
        self.nGesturesEdit.setObjectName("nGesturesEdit")
        self.label = QtWidgets.QLabel(self.gesturesFrame)
        self.label.setGeometry(QtCore.QRect(30, 70, 58, 14))
        self.label.setObjectName("label")
        self.gesture1Box = QtWidgets.QComboBox(self.gesturesFrame)
        self.gesture1Box.setGeometry(QtCore.QRect(30, 90, 78, 24))
        self.gesture1Box.setObjectName("gesture1Box")
        self.gesture1Box.addItem("")
        self.gesture1Box.addItem("")
        self.gesture1Box.addItem("")
        self.gesture1Box.addItem("")
        self.gesture1Box.addItem("")
        self.gesture1Box.addItem("")
        self.firstLabel = QtWidgets.QLabel(self.gesturesFrame)
        self.firstLabel.setGeometry(QtCore.QRect(0, 95, 21, 16))
        self.firstLabel.setObjectName("firstLabel")
        self.gesture2Box = QtWidgets.QComboBox(self.gesturesFrame)
        self.gesture2Box.setGeometry(QtCore.QRect(30, 120, 78, 24))
        self.gesture2Box.setObjectName("gesture2Box")
        self.gesture2Box.addItem("")
        self.gesture2Box.addItem("")
        self.gesture2Box.addItem("")
        self.gesture2Box.addItem("")
        self.gesture2Box.addItem("")
        self.gesture2Box.addItem("")
        self.gesture5Box = QtWidgets.QComboBox(self.gesturesFrame)
        self.gesture5Box.setGeometry(QtCore.QRect(30, 210, 78, 24))
        self.gesture5Box.setObjectName("gesture5Box")
        self.gesture5Box.addItem("")
        self.gesture5Box.addItem("")
        self.gesture5Box.addItem("")
        self.gesture5Box.addItem("")
        self.gesture5Box.addItem("")
        self.gesture5Box.addItem("")
        self.gesture4Box = QtWidgets.QComboBox(self.gesturesFrame)
        self.gesture4Box.setGeometry(QtCore.QRect(30, 180, 78, 24))
        self.gesture4Box.setObjectName("gesture4Box")
        self.gesture4Box.addItem("")
        self.gesture4Box.addItem("")
        self.gesture4Box.addItem("")
        self.gesture4Box.addItem("")
        self.gesture4Box.addItem("")
        self.gesture4Box.addItem("")
        self.gesture3Box = QtWidgets.QComboBox(self.gesturesFrame)
        self.gesture3Box.setGeometry(QtCore.QRect(30, 150, 78, 24))
        self.gesture3Box.setObjectName("gesture3Box")
        self.gesture3Box.addItem("")
        self.gesture3Box.addItem("")
        self.gesture3Box.addItem("")
        self.gesture3Box.addItem("")
        self.gesture3Box.addItem("")
        self.gesture3Box.addItem("")
        self.secondLabel = QtWidgets.QLabel(self.gesturesFrame)
        self.secondLabel.setGeometry(QtCore.QRect(0, 125, 21, 16))
        self.secondLabel.setObjectName("secondLabel")
        self.thirdLabel = QtWidgets.QLabel(self.gesturesFrame)
        self.thirdLabel.setGeometry(QtCore.QRect(0, 155, 21, 16))
        self.thirdLabel.setObjectName("thirdLabel")
        self.fourthLabel = QtWidgets.QLabel(self.gesturesFrame)
        self.fourthLabel.setGeometry(QtCore.QRect(0, 185, 21, 16))
        self.fourthLabel.setObjectName("fourthLabel")
        self.fifthLabel = QtWidgets.QLabel(self.gesturesFrame)
        self.fifthLabel.setGeometry(QtCore.QRect(0, 215, 21, 16))
        self.fifthLabel.setObjectName("fifthLabel")
        self.casualCheckBox = QtWidgets.QCheckBox(self.gesturesFrame)
        self.casualCheckBox.setGeometry(QtCore.QRect(30, 240, 131, 21))
        self.casualCheckBox.setObjectName("casualCheckBox")
        self.nGesturesLabel.raise_()
        self.nGesturesEdit.raise_()
        self.label.raise_()
        self.gesture1Box.raise_()
        self.firstLabel.raise_()
        self.gesture2Box.raise_()
        self.gesture5Box.raise_()
        self.gesture4Box.raise_()
        self.gesture3Box.raise_()
        self.secondLabel.raise_()
        self.thirdLabel.raise_()
        self.fourthLabel.raise_()
        self.fifthLabel.raise_()
        self.casualCheckBox.raise_()
        self.gesturesFrame_2 = QtWidgets.QFrame(self.page)
        self.gesturesFrame_2.setGeometry(QtCore.QRect(680, 70, 221, 291))
        self.gesturesFrame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.gesturesFrame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.gesturesFrame_2.setObjectName("gesturesFrame_2")
        self.sensorsLabel = QtWidgets.QLabel(self.gesturesFrame_2)
        self.sensorsLabel.setGeometry(QtCore.QRect(30, 20, 81, 16))
        self.sensorsLabel.setObjectName("sensorsLabel")
        self.casualCheckBox_2 = QtWidgets.QCheckBox(self.gesturesFrame_2)
        self.casualCheckBox_2.setGeometry(QtCore.QRect(30, 40, 71, 21))
        self.casualCheckBox_2.setObjectName("casualCheckBox_2")
        self.casualCheckBox_3 = QtWidgets.QCheckBox(self.gesturesFrame_2)
        self.casualCheckBox_3.setGeometry(QtCore.QRect(30, 60, 71, 21))
        self.casualCheckBox_3.setObjectName("casualCheckBox_3")
        self.casualCheckBox_4 = QtWidgets.QCheckBox(self.gesturesFrame_2)
        self.casualCheckBox_4.setGeometry(QtCore.QRect(30, 80, 101, 21))
        self.casualCheckBox_4.setObjectName("casualCheckBox_4")
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.stackedWidget.addWidget(self.page_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 970, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.startButton.clicked.connect(self.changePage)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def changePage(self, MainWindow):
        self.stackedWidget.setCurrentIndex(1)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Experimenter GUI"))
        self.titleConfigurationLabel.setText(_translate("MainWindow", "Configuration"))
        self.startButton.setText(_translate("MainWindow", "Start"))
        self.nameLabel.setText(_translate("MainWindow", "Name"))
        self.ageLabel.setText(_translate("MainWindow", "Age"))
        self.genderLabel.setText(_translate("MainWindow", "Gender"))
        self.heightLabel.setText(_translate("MainWindow", "Height"))
        self.weightLabel.setText(_translate("MainWindow", "Weight"))
        self.genderBox.setItemText(0, _translate("MainWindow", "M"))
        self.genderBox.setItemText(1, _translate("MainWindow", "F"))
        self.genderBox.setItemText(2, _translate("MainWindow", "Other"))
        self.nGesturesLabel.setText(_translate("MainWindow", "Number of Gestures"))
        self.label.setText(_translate("MainWindow", "Gestures"))
        self.gesture1Box.setItemText(0, _translate("MainWindow", "None"))
        self.gesture1Box.setItemText(1, _translate("MainWindow", "Drinking"))
        self.gesture1Box.setItemText(2, _translate("MainWindow", "Pouring"))
        self.gesture1Box.setItemText(3, _translate("MainWindow", "Sitting Down"))
        self.gesture1Box.setItemText(4, _translate("MainWindow", "Standing Up"))
        self.gesture1Box.setItemText(5, _translate("MainWindow", "Walking"))
        self.firstLabel.setText(_translate("MainWindow", "1st"))
        self.gesture2Box.setItemText(0, _translate("MainWindow", "None"))
        self.gesture2Box.setItemText(1, _translate("MainWindow", "Drinking"))
        self.gesture2Box.setItemText(2, _translate("MainWindow", "Pouring"))
        self.gesture2Box.setItemText(3, _translate("MainWindow", "Sitting Down"))
        self.gesture2Box.setItemText(4, _translate("MainWindow", "Standing Up"))
        self.gesture2Box.setItemText(5, _translate("MainWindow", "Walking"))
        self.gesture5Box.setItemText(0, _translate("MainWindow", "None"))
        self.gesture5Box.setItemText(1, _translate("MainWindow", "Drinking"))
        self.gesture5Box.setItemText(2, _translate("MainWindow", "Pouring"))
        self.gesture5Box.setItemText(3, _translate("MainWindow", "Sitting Down"))
        self.gesture5Box.setItemText(4, _translate("MainWindow", "Standing Up"))
        self.gesture5Box.setItemText(5, _translate("MainWindow", "Walking"))
        self.gesture4Box.setItemText(0, _translate("MainWindow", "None"))
        self.gesture4Box.setItemText(1, _translate("MainWindow", "Drinking"))
        self.gesture4Box.setItemText(2, _translate("MainWindow", "Pouring"))
        self.gesture4Box.setItemText(3, _translate("MainWindow", "Sitting Down"))
        self.gesture4Box.setItemText(4, _translate("MainWindow", "Standing Up"))
        self.gesture4Box.setItemText(5, _translate("MainWindow", "Walking"))
        self.gesture3Box.setItemText(0, _translate("MainWindow", "None"))
        self.gesture3Box.setItemText(1, _translate("MainWindow", "Drinking"))
        self.gesture3Box.setItemText(2, _translate("MainWindow", "Pouring"))
        self.gesture3Box.setItemText(3, _translate("MainWindow", "Sitting Down"))
        self.gesture3Box.setItemText(4, _translate("MainWindow", "Standing Up"))
        self.gesture3Box.setItemText(5, _translate("MainWindow", "Walking"))
        self.secondLabel.setText(_translate("MainWindow", "2nd"))
        self.thirdLabel.setText(_translate("MainWindow", "3rd"))
        self.fourthLabel.setText(_translate("MainWindow", "4th"))
        self.fifthLabel.setText(_translate("MainWindow", "5th"))
        self.casualCheckBox.setText(_translate("MainWindow", "Casual Sequence"))
        self.sensorsLabel.setText(_translate("MainWindow", "Sensors Used"))
        self.casualCheckBox_2.setText(_translate("MainWindow", "Kinect"))
        self.casualCheckBox_3.setText(_translate("MainWindow", "MOCAP"))
        self.casualCheckBox_4.setText(_translate("MainWindow", "Smartwatch"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
